// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJSWnkRdQCMlCi_7bTkiEfzNXaJRWBMcg',
    appId: '1:338256818032:web:29c6d7ff71d3ff386029b5',
    messagingSenderId: '338256818032',
    projectId: 'calerdar-date',
    authDomain: 'calerdar-date.firebaseapp.com',
    storageBucket: 'calerdar-date.appspot.com',
    measurementId: 'G-V9528V93ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOGSPDF930jBSWsCRBUe1A4w_gh-YjHDE',
    appId: '1:338256818032:android:640560bfc9acbe756029b5',
    messagingSenderId: '338256818032',
    projectId: 'calerdar-date',
    storageBucket: 'calerdar-date.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAGwcSZ39oYZRMHehwc7ByfargdrENGuY',
    appId: '1:338256818032:ios:3e38fb97fe5e938f6029b5',
    messagingSenderId: '338256818032',
    projectId: 'calerdar-date',
    storageBucket: 'calerdar-date.appspot.com',
    iosClientId: '338256818032-fc0agj4d7m1p00nnjbd6be7ks7ps6te1.apps.googleusercontent.com',
    iosBundleId: 'com.example.register',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAGwcSZ39oYZRMHehwc7ByfargdrENGuY',
    appId: '1:338256818032:ios:3e38fb97fe5e938f6029b5',
    messagingSenderId: '338256818032',
    projectId: 'calerdar-date',
    storageBucket: 'calerdar-date.appspot.com',
    iosClientId: '338256818032-fc0agj4d7m1p00nnjbd6be7ks7ps6te1.apps.googleusercontent.com',
    iosBundleId: 'com.example.register',
  );
}
